import fs from 'fs';

const renderPage = (title, desc, h1, body) => `---
import BaseLayout from "../layouts/BaseLayout.astro";
import InvoiceGenerator from "../components/InvoiceGenerator";
const schemas = [];
---
<BaseLayout title="${title}" description="${desc}">
  <div class="max-w-4xl mx-auto px-6 pt-20 pb-10 text-center">
    <h1 class="text-5xl md:text-6xl font-extrabold text-slate-900 tracking-tight mb-6">${h1}</h1>
  </div>
  <InvoiceGenerator client:load />
  <article class="py-20 bg-white border-t border-slate-100">
    <div class="max-w-3xl mx-auto px-6 prose prose-slate prose-lg">
      ${body}
    </div>
  </article>
</BaseLayout>
`;

const page1 = renderPage(
  "Free Invoice Generator — No Signup Required",
  "Use this free invoice generator to create professional PDFs instantly. No signup, no watermarks, no limits. Fast, secure, and ready to download or share.",
  "Free Invoice Generator",
  `
    <p>Welcome to the ultimate free invoice generator. If you run a small business, work as a freelancer, or provide contractor services, managing your billing effectively is crucial to maintaining a steady cash flow. The ability to create invoice documents quickly and professionally directly impacts how fast you get paid. Our free invoice generator simplifies this entire process, allowing you to generate a PDF invoice in seconds without the hassle of downloading software or paying monthly subscription fees.</p>
    <p>Many business owners struggle with complex accounting platforms when all they really need is a simple billing solution. This free invoice generator provides exactly that—a streamlined, intuitive interface where you can input your details, add line items, and instantly download a professional document. By utilizing our tool, you eliminate the need to manually format an invoice template in Word or Excel, saving you hours of administrative work each month.</p>
    
    <h2>Is This Free Invoice Generator Really Free?</h2>
    <p>When searching for a free invoice generator, a common concern is hidden costs. We built this platform to address the fear of hidden fees head-on. Yes, this free invoice generator is genuinely 100% free to use. There are no surprise paywalls right before you try to download your PDF invoice, no mandatory account creation gates, and absolutely zero subscription requirements.</p>
    <p>Most platforms operate on a freemium model. They might let you create one or two documents before demanding a credit card, or they might allow unlimited generation but stamp a massive watermark across your billing documents. We believe that small business tools should be accessible. When you create invoice documents here, you retain full professional branding with no watermarks and no usage limits.</p>
    
    <h2>What's Included in the Free Plan</h2>
    <p>Because there are no paid tiers, our "free plan" includes every single feature available on the platform. When using this free invoice generator, you get unrestricted access to premium-level functionality. You can add unlimited line items, customize your tax rates (including specific US sales tax fields), and input your Employer Identification Number (EIN) for tax compliance.</p>
    <p>Furthermore, you have the ability to upload your own business logo to personalize your invoice template. The live preview updates in real-time, allowing you to see exactly what your client will receive. Once finished, you can download a high-quality PDF invoice or share it directly via WhatsApp. Everything is processed locally in your browser for maximum privacy and speed.</p>
    
    <h2>How It Compares to Paid Invoice Software</h2>
    <p>It's important to understand how our free invoice generator stacks up against industry giants like FreshBooks, Zoho Invoice, and Wave. While those platforms offer comprehensive accounting suites (including expense tracking and bank reconciliation), they often charge monthly fees ranging from $15 to $30. If your only goal is to create invoice PDFs and send them to clients, you are overpaying for features you don't use.</p>
    <p>Our tool focuses purely on billing document generation. Unlike Zoho or Wave, which require you to create an account, verify your email, and onboard your business details before creating a single document, our platform lets you start typing immediately. The output is an identical, professional PDF invoice that serves the exact same legal and financial purpose as one generated by expensive software.</p>
    
    <h2>Frequently Asked Questions About Free Invoicing</h2>
    <div itemscope itemtype="https://schema.org/FAQPage">
      <div itemscope itemprop="mainEntity" itemtype="https://schema.org/Question">
        <h3 itemprop="name">Are there any hidden fees to use this tool?</h3>
        <div itemscope itemprop="acceptedAnswer" itemtype="https://schema.org/Answer">
          <p itemprop="text">No, there are absolutely zero hidden fees. This free invoice generator is fully accessible without a credit card. We do not charge for downloads, and there are no premium features locked behind a paywall. Everything you see is free forever.</p>
        </div>
      </div>
      <div itemscope itemprop="mainEntity" itemtype="https://schema.org/Question">
        <h3 itemprop="name">Will my final PDF have a watermark?</h3>
        <div itemscope itemprop="acceptedAnswer" itemtype="https://schema.org/Answer">
          <p itemprop="text">Your generated PDF invoice will never contain our watermark or branding. We understand that maintaining a professional image is critical for your business, so the document will only display the logo and details you choose to include.</p>
        </div>
      </div>
      <div itemscope itemprop="mainEntity" itemtype="https://schema.org/Question">
        <h3 itemprop="name">How many invoices can I create for free?</h3>
        <div itemscope itemprop="acceptedAnswer" itemtype="https://schema.org/Answer">
          <p itemprop="text">You can create an unlimited number of billing documents. Whether you need to create invoice PDFs once a month or fifty times a day, there are no usage caps or monthly limits enforced on this free invoice generator.</p>
        </div>
      </div>
      <div itemscope itemprop="mainEntity" itemtype="https://schema.org/Question">
        <h3 itemprop="name">Do I need to create an account?</h3>
        <div itemscope itemprop="acceptedAnswer" itemtype="https://schema.org/Answer">
          <p itemprop="text">No signup is required. You do not need to provide an email address or create a password to use the tool. Simply open the webpage, fill out your invoice template, and instantly download your file.</p>
        </div>
      </div>
      <div itemscope itemprop="mainEntity" itemtype="https://schema.org/Question">
        <h3 itemprop="name">Is my financial data secure?</h3>
        <div itemscope itemprop="acceptedAnswer" itemtype="https://schema.org/Answer">
          <p itemprop="text">Yes, your data is entirely secure because this free invoice generator processes everything locally in your web browser. Your client information, line items, and financial totals are never sent to or stored on our servers.</p>
        </div>
      </div>
      <div itemscope itemprop="mainEntity" itemtype="https://schema.org/Question">
        <h3 itemprop="name">Can I use this for international clients?</h3>
        <div itemscope itemprop="acceptedAnswer" itemtype="https://schema.org/Answer">
          <p itemprop="text">Absolutely. You can customize the currency symbol, adjust the tax percentage for VAT or GST, and modify the payment terms to suit international billing requirements when you create invoice documents for clients abroad.</p>
        </div>
      </div>
    </div>
  `
);

const page2 = renderPage(
  "Invoice Generator Free — Unlimited Invoices",
  "Looking for an invoice generator free of charge? Create unlimited invoices with our tool. No hidden limits, no paywalls, no watermarks, no signup needed.",
  "Invoice Generator Free",
  `
    <p>Finding a reliable invoice generator free of strict limitations is surprisingly difficult. As a freelancer, contractor, or small business owner, your time is best spent doing the actual work that generates revenue, not fighting with complicated billing software. We have developed this platform to provide a premium invoice generator free from the common frustrations associated with online billing tools.</p>
    <p>Whether you need to quickly bill a client for a consulting session or generate a detailed PDF invoice for a massive construction project, this tool adapts to your needs. It serves as a blank, highly customizable invoice template that you can fill out in real-time. By separating the concept of a powerful invoice generator from the typical SaaS subscription model, we deliver immense value to self-employed professionals globally.</p>

    <h2>Invoice Generator Free — No Credit Card, No Trial, No Catch</h2>
    <p>The term "free" is heavily abused in the software industry. Most tools advertise themselves as an invoice generator free to use, only to hit you with a paywall right as you attempt to download your finished document. They rely on the sunk cost fallacy—knowing you just spent ten minutes typing in data, you're more likely to pay to get your file. We completely reject this deceptive practice.</p>
    <p>This is a truly invoice generator free of any catches. There is no trial period that expires after 14 days, and you will never be asked to enter a credit card. The core functionality—allowing you to create invoice documents and export them—is provided without restriction. We designed this tool to be a permanent, reliable utility in your freelance toolkit.</p>

    <h2>What You Can Do With a Free Invoice Generator</h2>
    <p>Despite being an invoice generator free of charge, the feature set is robust enough to handle complex billing scenarios. You can effortlessly manage your visual branding by uploading a company logo, which automatically scales to fit the professional layout. The tool allows you to add detailed line items with custom quantities and rates, automatically calculating subtotals and grand totals to prevent mathematical errors.</p>
    <p>Additionally, you can apply specific sales tax percentages, which is vital for compliance in many jurisdictions. The interface updates instantly, acting as a live invoice template so you can review the formatting before generating the final PDF invoice. Once verified, you can download the file locally or use the built-in WhatsApp sharing feature to send it directly to a client's smartphone for faster payment.</p>

    <h2>Limitations of Free Invoice Generators (And How We Avoid Them)</h2>
    <p>Traditionally, using an invoice generator free online comes with severe limitations. Competitors often restrict the number of clients you can bill, limit you to three invoices per month, or force a massive watermark onto your documents. These limitations make it impossible to maintain a professional appearance when dealing with high-value clients.</p>
    <p>We avoid these limitations by running the application entirely client-side. Because your browser does all the heavy lifting to generate the PDF invoice, our server costs remain incredibly low. This technical architecture allows us to provide an unrestricted, unlimited service. You get a clean, watermark-free document every single time, ensuring your business always looks its best without incurring unnecessary overhead.</p>

    <h2>Use Cases: Who Benefits from This Tool?</h2>
    <p><strong>Freelancers:</strong> Graphic designers, writers, and developers love this tool because it's fast. When a project wraps up, they can load the site, create invoice documents in under a minute, and send them off, minimizing administrative overhead.</p>
    <p><strong>Contractors:</strong> Plumbers, electricians, and tradespeople often need to bill clients on the job site. Because this is an invoice generator free of desktop constraints, it works perfectly on mobile browsers, allowing them to share a PDF invoice via WhatsApp before leaving the driveway.</p>
    <p><strong>Small Businesses:</strong> Retailers or boutique service providers who don't need heavy accounting software use our invoice template to handle occasional wholesale orders or custom services professionally and efficiently.</p>

    <h2>Frequently Asked Questions</h2>
    <div itemscope itemtype="https://schema.org/FAQPage">
      <div itemscope itemprop="mainEntity" itemtype="https://schema.org/Question">
        <h3 itemprop="name">Is this invoice generator free for commercial use?</h3>
        <div itemscope itemprop="acceptedAnswer" itemtype="https://schema.org/Answer">
          <p itemprop="text">Yes, it is entirely free for both personal and commercial use. You can use it to bill clients for your registered business, LLC, or freelance services without worrying about licensing fees or commercial usage restrictions.</p>
        </div>
      </div>
      <div itemscope itemprop="mainEntity" itemtype="https://schema.org/Question">
        <h3 itemprop="name">Do I have to pay to remove watermarks?</h3>
        <div itemscope itemprop="acceptedAnswer" itemtype="https://schema.org/Answer">
          <p itemprop="text">No payment is required because we do not add watermarks in the first place. Every PDF invoice you generate is completely clean, featuring only the business logo and branding information that you manually upload.</p>
        </div>
      </div>
      <div itemscope itemprop="mainEntity" itemtype="https://schema.org/Question">
        <h3 itemprop="name">Does it work offline?</h3>
        <div itemscope itemprop="acceptedAnswer" itemtype="https://schema.org/Answer">
          <p itemprop="text">While you need an internet connection to initially load the webpage, the actual generation of the PDF happens locally in your browser. However, it is recommended to remain online to ensure features like WhatsApp sharing function properly.</p>
        </div>
      </div>
      <div itemscope itemprop="mainEntity" itemtype="https://schema.org/Question">
        <h3 itemprop="name">Can I save my invoice template?</h3>
        <div itemscope itemprop="acceptedAnswer" itemtype="https://schema.org/Answer">
          <p itemprop="text">Currently, the tool acts as a single-session generator to protect your privacy. Data is not saved between sessions, meaning you start with a fresh template each time. We recommend keeping a copy of your downloaded PDF for your records.</p>
        </div>
      </div>
      <div itemscope itemprop="mainEntity" itemtype="https://schema.org/Question">
        <h3 itemprop="name">How do I add tax to my bill?</h3>
        <div itemscope itemprop="acceptedAnswer" itemtype="https://schema.org/Answer">
          <p itemprop="text">There is a dedicated tax field located at the bottom of the line items section. Simply enter your local tax percentage, and the invoice generator free calculator will automatically add it to your grand total.</p>
        </div>
      </div>
      <div itemscope itemprop="mainEntity" itemtype="https://schema.org/Question">
        <h3 itemprop="name">What file format does it output?</h3>
        <div itemscope itemprop="acceptedAnswer" itemtype="https://schema.org/Answer">
          <p itemprop="text">The tool exclusively outputs a high-resolution, print-ready PDF invoice. This is the industry standard for billing documents, ensuring that your formatting looks identical on any device your client uses to view it.</p>
        </div>
      </div>
    </div>
  `
);

fs.writeFileSync('src/pages/free-invoice-generator.astro', page1);
fs.writeFileSync('src/pages/invoice-generator-free.astro', page2);
console.log('Done 1/3');
